//! Pure, I/O-free winner-determination state machine for ATTACH v2 fencing
//! (`#18-2`). Replaces `engine/mod.rs`'s single `active: Arc<AtomicBool>`
//! compare-exchange, which cannot express the invariant a stale async
//! completion needs (a delayed `TargetConnected` for an already-superseded
//! attempt must not resurrect it) — see `ISEKAI_PIPE_DESIGN.md`/task `#18`'s
//! ChatGPT second-opinion consultation (2026-07-08) for the full rationale.
//!
//! This module only decides *what should happen*
//! ([`AttachEffect`]) in response to *what happened*
//! ([`AttachEvent`]); it never touches a socket, a clock, or an RNG.
//! `#18-3` wires an actual effect executor (real TCP connects, real
//! `AttachReadyV2`/reject frame sends, real pending-activation timers) around
//! this reducer and replaces `engine/mod.rs`'s `active` flag with it.
//!
//! Winner rule (module docs of task `#18`, not simple first/last-write-wins):
//! **within one `ConnectionGeneration`, the first authenticated ATTACH_HELLO
//! wins; a strictly larger generation may supersede an earlier generation
//! that has not yet reached [`AttachState::Established`].** Superseding always
//! goes through [`AttachState::ClosingForSupersede`] first — the old lease's
//! resources must actually finish tearing down (`LeaseStopped`) before the
//! new attempt's `ConnectTarget` effect is issued, so at most one target TCP
//! connection *for a given session* is ever attempting/active at a time.
//!
//! **Epic N-5**: this arbiter holds one independent state slot *per
//! `session_id`* (`sessions: HashMap<SessionId, AttachState>`), not a single
//! global slot for the whole target — see `ISEKAI_PIPE_DESIGN.md` §8 Epic
//! N-5 for why. Everything above (the winner rule, superseding, stale-async
//! safety) applies independently within one session's entry; different
//! `session_id`s never interact with each other here at all. Absence of an
//! entry for a `session_id` is this module's "vacant" (there used to be an
//! explicit `AttachState::Vacant` for the single-slot design; a per-session
//! table just omits the key instead).

use std::collections::HashMap;

use isekai_protocol::attach::{AttachKey, AttachRejectReason, AttachToken};
use isekai_protocol::SessionId;

/// Correlates one accepted attempt's underlying resources (in-flight target
/// TCP connect, then — once established — the relay task) across the
/// attempt's lifetime, independent of retries at the `AttachKey` level.
/// Minted by [`AttachArbiter`] itself so completions the effect executor
/// reports back (`TargetConnected`/`TargetConnectFailed`/`LeaseStopped`) can
/// always be checked against the arbiter's *current* notion of "the lease
/// that matters", even if it arrives after the arbiter has already moved on.
/// Unique across every session (not just within one), minted from one
/// monotonic counter shared by the whole arbiter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct LeaseId(u64);

/// Opaque handle to the target TCP connection an effect executor already
/// established for a given lease (assigned by the executor, not this
/// module — this reducer never creates a real socket).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TargetHandleId(pub u64);

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AttachState {
    Connecting {
        key: AttachKey,
        lease: LeaseId,
    },
    /// `AttachReadyV2` has been sent but `AttachActivate` has not yet been
    /// received — the ambiguous window `#12` discovered. No SSH user data
    /// flows for `target` while in this state (`#18-3`'s job to enforce).
    PendingActivation {
        key: AttachKey,
        lease: LeaseId,
        attach_token: AttachToken,
        target: TargetHandleId,
    },
    Established {
        key: AttachKey,
        lease: LeaseId,
    },
    /// A strictly larger generation than `old_lease`'s has been accepted in
    /// principle, but `old_lease`'s resources have not finished tearing down
    /// yet — `next`'s `ConnectTarget` effect is deliberately withheld until
    /// `LeaseStopped { lease: old_lease }` arrives, so this session's target
    /// never sees two concurrent connection attempts at once.
    ClosingForSupersede {
        old_lease: LeaseId,
        next: AttachKey,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttachEvent {
    HelloReceived {
        key: AttachKey,
    },
    /// `attach_token` is generated by the effect executor (needs an RNG,
    /// which this I/O-free reducer deliberately has no access to) the moment
    /// the target TCP connect succeeds.
    TargetConnected {
        lease: LeaseId,
        target: TargetHandleId,
        attach_token: AttachToken,
    },
    TargetConnectFailed {
        lease: LeaseId,
    },
    Activated {
        key: AttachKey,
        attach_token: AttachToken,
    },
    CancelReceived {
        key: AttachKey,
    },
    LeaseStopped {
        lease: LeaseId,
    },
    /// The effect executor's pending-activation timer fired for `lease`
    /// without an `Activated` event arriving first.
    PendingExpired {
        lease: LeaseId,
    },
    /// The established relay session ended (target TCP died, or — for
    /// sessions that support resume — was ultimately discarded rather than
    /// resumed; the existing `SessionTable`/resume machinery outside this
    /// module owns that decision). Frees this lease's session entry entirely.
    RelayEnded {
        lease: LeaseId,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttachEffect {
    ConnectTarget { lease: LeaseId },
    /// Abandon whatever resources are associated with `lease`, whatever
    /// stage it is at (in-flight connect, pending-activation target, or an
    /// active relay task) — the effect executor looks up its own
    /// lease-keyed bookkeeping to know which.
    CancelLease { lease: LeaseId },
    /// `lease` lets the connection that eventually reaches `Established` for
    /// `key` report `AttachEvent::RelayEnded { lease }` later, without the
    /// executor needing a separate `key -> lease` lookup.
    SendReady { key: AttachKey, lease: LeaseId, attach_token: AttachToken },
    SendReject { key: AttachKey, reason: AttachRejectReason },
    /// Arm a pending-activation timer for `lease`; the executor feeds
    /// `AttachEvent::PendingExpired { lease }` back if it fires before
    /// `Activated` arrives. The timeout duration itself is operational
    /// config (mirrors `HELLO_TIMEOUT`/`--resume-window` today), not this
    /// pure module's concern.
    SchedulePendingTimeout { lease: LeaseId },
    /// Only ever emitted once, on the `Activated` transition into
    /// `Established` — before this point no SSH user data may flow for
    /// `target` (the ambiguous-window fix `#12` deferred to this task).
    StartRelay { lease: LeaseId, target: TargetHandleId },
}

/// Owns one [`AttachState`] slot per `session_id` plus the monotonic counter
/// that mints [`LeaseId`]s (shared across every session, so leases stay
/// globally unique). Deterministic given the sequence of `apply` calls (no
/// clock, no RNG), which is what makes the stale-async-completion and
/// concurrent-race invariants exhaustively unit-testable.
#[derive(Debug, Default)]
pub struct AttachArbiter {
    sessions: HashMap<SessionId, AttachState>,
    next_lease: u64,
}

impl AttachArbiter {
    pub fn new() -> Self {
        Self { sessions: HashMap::new(), next_lease: 0 }
    }

    /// The current state of one specific session's slot, if it has one.
    pub fn state_for(&self, session_id: SessionId) -> Option<&AttachState> {
        self.sessions.get(&session_id)
    }

    /// How many sessions currently hold a slot (connecting, pending, or
    /// established/parked — anything short of fully torn down) — used by
    /// the executor layer's admission control (`--max-sessions`, Epic N-5)
    /// and by `AttachRuntime::is_vacant`'s `--max-idle-lifetime` check.
    pub fn session_count(&self) -> usize {
        self.sessions.len()
    }

    pub fn has_session(&self, session_id: SessionId) -> bool {
        self.sessions.contains_key(&session_id)
    }

    fn mint_lease(&mut self) -> LeaseId {
        let id = LeaseId(self.next_lease);
        self.next_lease += 1;
        id
    }

    /// Finds which session's slot (if any) currently references `lease` —
    /// needed because `TargetConnected`/`TargetConnectFailed`/`LeaseStopped`/
    /// `PendingExpired`/`RelayEnded` only carry a `LeaseId`, not a
    /// `session_id`. A linear scan is deliberate: these events only occur at
    /// connect/disconnect boundaries (not per-byte), and the session count is
    /// bounded by `--max-sessions` (default 16), so this is cheap and avoids
    /// a second `lease -> session_id` index that would need to be kept in
    /// sync with every transition below.
    fn session_for_lease(&self, lease: LeaseId) -> Option<SessionId> {
        self.sessions.iter().find_map(|(session_id, state)| {
            let owns = match state {
                AttachState::Connecting { lease: l, .. } => *l == lease,
                AttachState::PendingActivation { lease: l, .. } => *l == lease,
                AttachState::Established { lease: l, .. } => *l == lease,
                AttachState::ClosingForSupersede { old_lease, .. } => *old_lease == lease,
            };
            owns.then_some(*session_id)
        })
    }

    pub fn apply(&mut self, event: AttachEvent) -> Vec<AttachEffect> {
        match event {
            AttachEvent::HelloReceived { key } => self.on_hello_received(key),
            AttachEvent::TargetConnected { lease, target, attach_token } => {
                self.on_target_connected(lease, target, attach_token)
            }
            AttachEvent::TargetConnectFailed { lease } => self.on_target_connect_failed(lease),
            AttachEvent::Activated { key, attach_token } => self.on_activated(key, attach_token),
            AttachEvent::CancelReceived { key } => self.on_cancel_received(key),
            AttachEvent::LeaseStopped { lease } => self.on_lease_stopped(lease),
            AttachEvent::PendingExpired { lease } => self.on_pending_expired(lease),
            AttachEvent::RelayEnded { lease } => self.on_relay_ended(lease),
        }
    }

    fn on_hello_received(&mut self, key: AttachKey) -> Vec<AttachEffect> {
        match self.sessions.get(&key.session_id).cloned() {
            None => {
                let lease = self.mint_lease();
                self.sessions.insert(key.session_id, AttachState::Connecting { key, lease });
                vec![AttachEffect::ConnectTarget { lease }]
            }
            Some(AttachState::Connecting { key: cur, lease }) => {
                self.decide_against_in_flight(key, cur, lease, None)
            }
            Some(AttachState::PendingActivation { key: cur, lease, attach_token, .. }) => {
                self.decide_against_in_flight(key, cur, lease, Some(attach_token))
            }
            // `key.session_id == cur.session_id` is guaranteed here (both
            // came from the same map entry) — a *different* session_id
            // always gets its own independent slot instead (Epic N-5), so
            // there is no cross-session `BusyOtherSession` case left here.
            Some(AttachState::Established { .. }) => {
                vec![AttachEffect::SendReject { key, reason: AttachRejectReason::AttachAlreadyEstablished }]
            }
            Some(AttachState::ClosingForSupersede { old_lease, next }) => {
                if key == next {
                    // Retransmit of the very attempt already driving the
                    // supersede; still waiting on the old lease to stop.
                    vec![]
                } else if key.generation > next.generation {
                    // An even newer generation arrived before the previous
                    // supersede finished draining — just update which
                    // attempt wins once `old_lease` actually stops; the
                    // cancellation already in flight for `old_lease` covers
                    // this too (only one lease is ever being torn down).
                    self.sessions.insert(key.session_id, AttachState::ClosingForSupersede { old_lease, next: key });
                    vec![]
                } else if key.generation < next.generation {
                    vec![AttachEffect::SendReject {
                        key,
                        reason: AttachRejectReason::StaleGeneration { current_generation: next.generation },
                    }]
                } else {
                    // Same generation, different attempt_id: `next` already
                    // claims this generation.
                    vec![AttachEffect::SendReject { key, reason: AttachRejectReason::AlreadyAttached }]
                }
            }
        }
    }

    /// Shared decision for `HelloReceived` while some attempt `cur` (lease
    /// `cur_lease`) is `Connecting` or `PendingActivation` for the *same*
    /// `session_id` as `key` (guaranteed by the caller's map lookup) — every
    /// state where `cur` has not yet reached `Established` and could still
    /// be fenced by a strictly larger generation.
    fn decide_against_in_flight(
        &mut self,
        key: AttachKey,
        cur: AttachKey,
        cur_lease: LeaseId,
        pending_attach_token: Option<AttachToken>,
    ) -> Vec<AttachEffect> {
        if key.generation < cur.generation {
            return vec![AttachEffect::SendReject {
                key,
                reason: AttachRejectReason::StaleGeneration { current_generation: cur.generation },
            }];
        }
        if key.generation == cur.generation {
            return if key.attempt_id == cur.attempt_id {
                match pending_attach_token {
                    // Retransmit of the same attempt that already has a
                    // token: resend AttachReadyV2. No new effect if we're
                    // still just Connecting (nothing to resend yet).
                    Some(attach_token) => vec![AttachEffect::SendReady { key, lease: cur_lease, attach_token }],
                    None => vec![],
                }
            } else {
                vec![AttachEffect::SendReject { key, reason: AttachRejectReason::AlreadyAttached }]
            };
        }
        // key.generation > cur.generation: supersede `cur`, but only once
        // its lease has actually finished tearing down.
        self.sessions.insert(key.session_id, AttachState::ClosingForSupersede { old_lease: cur_lease, next: key });
        vec![AttachEffect::CancelLease { lease: cur_lease }]
    }

    fn on_target_connected(
        &mut self,
        lease: LeaseId,
        target: TargetHandleId,
        attach_token: AttachToken,
    ) -> Vec<AttachEffect> {
        let Some(session_id) = self.session_for_lease(lease) else { return vec![] };
        let Some(AttachState::Connecting { key, .. }) = self.sessions.get(&session_id).cloned() else {
            return vec![];
        };
        self.sessions.insert(session_id, AttachState::PendingActivation { key, lease, attach_token, target });
        vec![AttachEffect::SendReady { key, lease, attach_token }, AttachEffect::SchedulePendingTimeout { lease }]
    }

    fn on_target_connect_failed(&mut self, lease: LeaseId) -> Vec<AttachEffect> {
        let Some(session_id) = self.session_for_lease(lease) else { return vec![] };
        let Some(AttachState::Connecting { key, .. }) = self.sessions.get(&session_id).cloned() else {
            return vec![];
        };
        self.sessions.remove(&session_id);
        vec![AttachEffect::SendReject { key, reason: AttachRejectReason::Target }]
    }

    fn on_activated(&mut self, key: AttachKey, attach_token: AttachToken) -> Vec<AttachEffect> {
        let Some(AttachState::PendingActivation { key: cur, lease, attach_token: cur_token, target }) =
            self.sessions.get(&key.session_id).cloned()
        else {
            return vec![];
        };
        if cur != key || !cur_token.ct_eq(&attach_token) {
            // Stray/late activation for an attempt that is no longer
            // current (or a guessed token) — ignore rather than let it
            // mutate state it doesn't own.
            return vec![];
        }
        self.sessions.insert(key.session_id, AttachState::Established { key, lease });
        vec![AttachEffect::StartRelay { lease, target }]
    }

    fn on_cancel_received(&mut self, key: AttachKey) -> Vec<AttachEffect> {
        match self.sessions.get(&key.session_id) {
            Some(AttachState::Connecting { key: cur, lease }) if *cur == key => {
                let lease = *lease;
                self.sessions.remove(&key.session_id);
                vec![AttachEffect::CancelLease { lease }]
            }
            Some(AttachState::PendingActivation { key: cur, lease, .. }) if *cur == key => {
                let lease = *lease;
                self.sessions.remove(&key.session_id);
                vec![AttachEffect::CancelLease { lease }]
            }
            // Established never yields to CANCEL (module docs); every other
            // state either doesn't match `key` exactly or has nothing live
            // to cancel yet (`ClosingForSupersede` — see module docs: CANCEL
            // is a best-effort optimization, not a safety mechanism, so
            // leaving `next` unaffected here is acceptable).
            _ => vec![],
        }
    }

    fn on_lease_stopped(&mut self, lease: LeaseId) -> Vec<AttachEffect> {
        let Some(session_id) = self.session_for_lease(lease) else { return vec![] };
        let Some(AttachState::ClosingForSupersede { next, .. }) = self.sessions.get(&session_id).cloned() else {
            return vec![];
        };
        let new_lease = self.mint_lease();
        self.sessions.insert(session_id, AttachState::Connecting { key: next, lease: new_lease });
        vec![AttachEffect::ConnectTarget { lease: new_lease }]
    }

    fn on_pending_expired(&mut self, lease: LeaseId) -> Vec<AttachEffect> {
        let Some(session_id) = self.session_for_lease(lease) else { return vec![] };
        if !matches!(self.sessions.get(&session_id), Some(AttachState::PendingActivation { .. })) {
            return vec![];
        }
        self.sessions.remove(&session_id);
        vec![AttachEffect::CancelLease { lease }]
    }

    fn on_relay_ended(&mut self, lease: LeaseId) -> Vec<AttachEffect> {
        let Some(session_id) = self.session_for_lease(lease) else { return vec![] };
        if !matches!(self.sessions.get(&session_id), Some(AttachState::Established { .. })) {
            return vec![];
        }
        self.sessions.remove(&session_id);
        vec![]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use isekai_protocol::attach::{AttemptId, ConnectionGeneration};
    use isekai_protocol::SessionId;

    fn sid(b: u8) -> SessionId {
        SessionId::from_bytes([b; 16])
    }

    fn aid(b: u8) -> AttemptId {
        AttemptId::from_bytes([b; 16])
    }

    fn key(session: u8, generation: u64, attempt: u8) -> AttachKey {
        AttachKey { session_id: sid(session), generation: ConnectionGeneration::new(generation), attempt_id: aid(attempt) }
    }

    fn token(b: u8) -> AttachToken {
        AttachToken::new([b; 16])
    }

    #[test]
    fn vacant_accepts_first_hello() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        let effects = a.apply(AttachEvent::HelloReceived { key: k });
        assert_eq!(effects, vec![AttachEffect::ConnectTarget { lease: LeaseId(0) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: k, lease: LeaseId(0) }));
    }

    #[test]
    fn full_happy_path_reaches_established_and_starts_relay() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let tok = token(9);
        let effects = a.apply(AttachEvent::TargetConnected {
            lease: LeaseId(0),
            target: TargetHandleId(100),
            attach_token: tok,
        });
        assert_eq!(
            effects,
            vec![
                AttachEffect::SendReady { key: k, lease: LeaseId(0), attach_token: tok },
                AttachEffect::SchedulePendingTimeout { lease: LeaseId(0) }
            ]
        );
        let effects = a.apply(AttachEvent::Activated { key: k, attach_token: tok });
        assert_eq!(effects, vec![AttachEffect::StartRelay { lease: LeaseId(0), target: TargetHandleId(100) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Established { key: k, lease: LeaseId(0) }));
    }

    #[test]
    fn concurrent_race_same_generation_first_commit_wins() {
        // #19: direct and relay candidates share one generation; whichever
        // HELLO the server processes first wins, the other is ALREADY_ATTACHED.
        let mut a = AttachArbiter::new();
        let winner = key(1, 5, 1);
        let loser = key(1, 5, 2);
        a.apply(AttachEvent::HelloReceived { key: winner });
        let effects = a.apply(AttachEvent::HelloReceived { key: loser });
        assert_eq!(
            effects,
            vec![AttachEffect::SendReject { key: loser, reason: AttachRejectReason::AlreadyAttached }]
        );
        // Winner's in-flight attempt is untouched.
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: winner, lease: LeaseId(0) }));
    }

    #[test]
    fn stale_generation_is_rejected_with_current_generation() {
        let mut a = AttachArbiter::new();
        a.apply(AttachEvent::HelloReceived { key: key(1, 5, 1) });
        let effects = a.apply(AttachEvent::HelloReceived { key: key(1, 3, 9) });
        assert_eq!(
            effects,
            vec![AttachEffect::SendReject {
                key: key(1, 3, 9),
                reason: AttachRejectReason::StaleGeneration { current_generation: ConnectionGeneration::new(5) }
            }]
        );
    }

    #[test]
    fn different_sessions_are_fully_independent() {
        // Epic N-5: a second, genuinely different session_id must get its
        // own slot immediately rather than being fenced out by the first.
        let mut a = AttachArbiter::new();
        let k1 = key(1, 0, 1);
        let k2 = key(2, 0, 1);
        let effects1 = a.apply(AttachEvent::HelloReceived { key: k1 });
        assert_eq!(effects1, vec![AttachEffect::ConnectTarget { lease: LeaseId(0) }]);
        let effects2 = a.apply(AttachEvent::HelloReceived { key: k2 });
        assert_eq!(effects2, vec![AttachEffect::ConnectTarget { lease: LeaseId(1) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: k1, lease: LeaseId(0) }));
        assert_eq!(a.state_for(sid(2)), Some(&AttachState::Connecting { key: k2, lease: LeaseId(1) }));
        assert_eq!(a.session_count(), 2);
    }

    #[test]
    fn relay_ended_for_one_session_does_not_affect_other_concurrent_sessions() {
        let mut a = AttachArbiter::new();
        let k1 = key(1, 0, 1);
        let k2 = key(2, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k1 });
        a.apply(AttachEvent::HelloReceived { key: k2 });
        let tok1 = token(1);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(0), target: TargetHandleId(1), attach_token: tok1 });
        a.apply(AttachEvent::Activated { key: k1, attach_token: tok1 });
        let tok2 = token(2);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(1), target: TargetHandleId(2), attach_token: tok2 });
        a.apply(AttachEvent::Activated { key: k2, attach_token: tok2 });
        assert!(matches!(a.state_for(sid(1)), Some(AttachState::Established { .. })));
        assert!(matches!(a.state_for(sid(2)), Some(AttachState::Established { .. })));

        let effects = a.apply(AttachEvent::RelayEnded { lease: LeaseId(0) });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), None);
        assert!(matches!(a.state_for(sid(2)), Some(AttachState::Established { .. })));
        assert_eq!(a.session_count(), 1);
    }

    #[test]
    fn larger_generation_supersedes_connecting_attempt_only_after_lease_stops() {
        // #25: ambiguous post-attach failure advances the generation; the
        // old lease must fully stop before the new attempt's target connect
        // is allowed to start (never two concurrent target connections).
        let mut a = AttachArbiter::new();
        let old = key(1, 5, 1);
        a.apply(AttachEvent::HelloReceived { key: old });

        let newer = key(1, 6, 1);
        let effects = a.apply(AttachEvent::HelloReceived { key: newer });
        assert_eq!(effects, vec![AttachEffect::CancelLease { lease: LeaseId(0) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::ClosingForSupersede { old_lease: LeaseId(0), next: newer }));

        // Stale completion for the old, already-superseded lease must not
        // resurrect it.
        let effects = a.apply(AttachEvent::TargetConnected {
            lease: LeaseId(0),
            target: TargetHandleId(1),
            attach_token: token(1),
        });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::ClosingForSupersede { old_lease: LeaseId(0), next: newer }));

        // Only once the old lease actually reports stopped does the new
        // attempt get to start connecting.
        let effects = a.apply(AttachEvent::LeaseStopped { lease: LeaseId(0) });
        assert_eq!(effects, vec![AttachEffect::ConnectTarget { lease: LeaseId(1) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: newer, lease: LeaseId(1) }));
    }

    #[test]
    fn even_newer_generation_arriving_during_supersede_updates_next() {
        let mut a = AttachArbiter::new();
        a.apply(AttachEvent::HelloReceived { key: key(1, 5, 1) });
        a.apply(AttachEvent::HelloReceived { key: key(1, 6, 1) });
        let effects = a.apply(AttachEvent::HelloReceived { key: key(1, 7, 1) });
        assert_eq!(effects, vec![]);
        assert_eq!(
            a.state_for(sid(1)),
            Some(&AttachState::ClosingForSupersede { old_lease: LeaseId(0), next: key(1, 7, 1) })
        );
        let effects = a.apply(AttachEvent::LeaseStopped { lease: LeaseId(0) });
        assert_eq!(effects, vec![AttachEffect::ConnectTarget { lease: LeaseId(1) }]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: key(1, 7, 1), lease: LeaseId(1) }));
    }

    #[test]
    fn stale_generation_arriving_during_supersede_is_rejected() {
        let mut a = AttachArbiter::new();
        a.apply(AttachEvent::HelloReceived { key: key(1, 5, 1) });
        a.apply(AttachEvent::HelloReceived { key: key(1, 7, 1) });
        let effects = a.apply(AttachEvent::HelloReceived { key: key(1, 6, 9) });
        assert_eq!(
            effects,
            vec![AttachEffect::SendReject {
                key: key(1, 6, 9),
                reason: AttachRejectReason::StaleGeneration { current_generation: ConnectionGeneration::new(7) }
            }]
        );
    }

    #[test]
    fn established_rejects_any_new_attach_for_same_session() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let tok = token(1);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(0), target: TargetHandleId(1), attach_token: tok });
        a.apply(AttachEvent::Activated { key: k, attach_token: tok });

        let effects = a.apply(AttachEvent::HelloReceived { key: key(1, 99, 5) });
        assert_eq!(
            effects,
            vec![AttachEffect::SendReject { key: key(1, 99, 5), reason: AttachRejectReason::AttachAlreadyEstablished }]
        );
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Established { key: k, lease: LeaseId(0) }));
    }

    #[test]
    fn established_only_yields_to_relay_ended_for_its_own_lease() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let tok = token(1);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(0), target: TargetHandleId(1), attach_token: tok });
        a.apply(AttachEvent::Activated { key: k, attach_token: tok });

        // Stale RelayEnded for an unrelated lease is ignored.
        let effects = a.apply(AttachEvent::RelayEnded { lease: LeaseId(99) });
        assert_eq!(effects, vec![]);
        assert!(matches!(a.state_for(sid(1)), Some(AttachState::Established { .. })));

        let effects = a.apply(AttachEvent::RelayEnded { lease: LeaseId(0) });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), None);
    }

    #[test]
    fn cancel_is_never_applied_to_established() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let tok = token(1);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(0), target: TargetHandleId(1), attach_token: tok });
        a.apply(AttachEvent::Activated { key: k, attach_token: tok });

        let effects = a.apply(AttachEvent::CancelReceived { key: k });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Established { key: k, lease: LeaseId(0) }));
    }

    #[test]
    fn cancel_exact_match_stops_connecting_attempt() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let effects = a.apply(AttachEvent::CancelReceived { key: k });
        assert_eq!(effects, vec![AttachEffect::CancelLease { lease: LeaseId(0) }]);
        assert_eq!(a.state_for(sid(1)), None);
    }

    #[test]
    fn cancel_does_not_affect_a_newer_generation_it_does_not_name() {
        // "CANCELが新しいgenerationに影響しない" (#18-7 scenario 8): a CANCEL
        // naming a now-stale key must not disturb whatever the arbiter has
        // since moved on to.
        let mut a = AttachArbiter::new();
        let old = key(1, 5, 1);
        a.apply(AttachEvent::HelloReceived { key: old });
        let newer = key(1, 6, 1);
        a.apply(AttachEvent::HelloReceived { key: newer }); // -> ClosingForSupersede
        let effects = a.apply(AttachEvent::CancelReceived { key: old });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::ClosingForSupersede { old_lease: LeaseId(0), next: newer }));
    }

    #[test]
    fn pending_expired_closes_target_and_frees_the_slot() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        a.apply(AttachEvent::TargetConnected {
            lease: LeaseId(0),
            target: TargetHandleId(1),
            attach_token: token(1),
        });
        let effects = a.apply(AttachEvent::PendingExpired { lease: LeaseId(0) });
        assert_eq!(effects, vec![AttachEffect::CancelLease { lease: LeaseId(0) }]);
        assert_eq!(a.state_for(sid(1)), None);
    }

    #[test]
    fn pending_expired_for_stale_lease_is_ignored() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        a.apply(AttachEvent::TargetConnected {
            lease: LeaseId(0),
            target: TargetHandleId(1),
            attach_token: token(1),
        });
        let effects = a.apply(AttachEvent::PendingExpired { lease: LeaseId(99) });
        assert_eq!(effects, vec![]);
        assert!(matches!(a.state_for(sid(1)), Some(AttachState::PendingActivation { .. })));
    }

    #[test]
    fn target_connect_failed_rejects_and_frees_the_slot() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let effects = a.apply(AttachEvent::TargetConnectFailed { lease: LeaseId(0) });
        assert_eq!(effects, vec![AttachEffect::SendReject { key: k, reason: AttachRejectReason::Target }]);
        assert_eq!(a.state_for(sid(1)), None);
    }

    #[test]
    fn activated_with_wrong_token_is_ignored() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        a.apply(AttachEvent::TargetConnected {
            lease: LeaseId(0),
            target: TargetHandleId(1),
            attach_token: token(1),
        });
        let effects = a.apply(AttachEvent::Activated { key: k, attach_token: token(0xEE) });
        assert_eq!(effects, vec![]);
        assert!(matches!(a.state_for(sid(1)), Some(AttachState::PendingActivation { .. })));
    }

    #[test]
    fn retransmitted_hello_while_connecting_is_a_no_op() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let effects = a.apply(AttachEvent::HelloReceived { key: k });
        assert_eq!(effects, vec![]);
        assert_eq!(a.state_for(sid(1)), Some(&AttachState::Connecting { key: k, lease: LeaseId(0) }));
    }

    #[test]
    fn retransmitted_hello_while_pending_activation_resends_ready() {
        let mut a = AttachArbiter::new();
        let k = key(1, 0, 1);
        a.apply(AttachEvent::HelloReceived { key: k });
        let tok = token(7);
        a.apply(AttachEvent::TargetConnected { lease: LeaseId(0), target: TargetHandleId(1), attach_token: tok });
        let effects = a.apply(AttachEvent::HelloReceived { key: k });
        assert_eq!(effects, vec![AttachEffect::SendReady { key: k, lease: LeaseId(0), attach_token: tok }]);
    }
}
